project:
  type: book
  output-dir: docs

book:
  title: "TSL Bioinformatics Training"
  author: "Dan MacLean"
  date: "June 2023"
  search: true
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - flippedclass.qmd
    - part: topics.qmd
      chapters:
        - genomics.qmd
        - onlinedatabases.qmd
        - dataviz.qmd
        - stats.qmd
        - nonfreq.qmd
        - ml.qmd
        - python.qmd
        - literacy.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

comments:
  hypothesis: true

