project:
  type: book
  output-dir: docs

book:
  title: "TSL Bioinformatics Training"
  author: "Dan MacLean"
  date: "June 2023"
  search: true
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - flippedclass.qmd
    - part: topics.qmd
      chapters:
        - genomics.qmd
        - onlinedatabases.qmd
        - dataviz.qmd
        - stats.qmd
        - nonfreq.qmd
        - ml.qmd
        - python.qmd
        - literacy.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    other-links:
      - text: Introduction to Genomics Chatbot
        href: https://tsl-bioinformatics.shinyapps.io/genomics_chatbot/
        target: _blank
      - text: Data Exploration and Visualisation Chatbot
        href: https://tsl-bioinformatics.shinyapps.io/datavixexp_chatbot/
        target: _blank
      - text: Understanding Statistics with Linear models Chatbot
        href: https://tsl-bioinformatics.shinyapps.io/test_elmer/
        target: _blank
      - text: Introduction to Non-Frequentist Statistics Chatbot
        href: https://tsl-bioinformatics.shinyapps.io/nonfreqstats_chatbot/
        target: _blank
  pdf:
    documentclass: scrreprt


comments:
  hypothesis: true

