# Introduction to Genomics

Genomics is a big field with wide use within biology. On the Global Plant Health M.Sc you are going to learn about a lot of applications of genomics technologies and data science skills underpin _all_ of those applications and analysis. So in this first, foundational topic we will look at how to run a basic genomics SNP calling pipeline on the Linux command line. This will include developing the basic skills to use the computer from the command line.



## The materials

As a source for this we will follow the excellent Data Carpentry Genomics Curriculum [https://datacarpentry.org/lessons/#genomics-workshop](https://datacarpentry.org/lessons/#genomics-workshop). We will do the following two lessons


  1. [Shell Genomics](https://datacarpentry.org/shell-genomics/)
  2. [Data Wrangling and Processing for Genomics](https://datacarpentry.org/wrangling-genomics/)
  
We will also use these materials  
  
  3. [Genome, Transcriptome and Structural Databases](https://danmaclean.github.io/databases/)

## For you to do

Parts 1 (Shell Genomics) and 2 (Data Wrangling) will be full contact time instructor led bootcamp courses. You should try reading the materials _before_ the course dates - it will help a great deal.

Part 3 is mostly an interactive tutorial, please work through that _before_ the scheduled discussion session in which we will go over as a group any questions and problems you may have had working through the materials.

