# How To Succeed In This Course {.unnumbered}

## How to make the most of the course

As this course is designed to be a practical one, you'll get the most out of it from practicing. The best way to do that is to come to the session prepared for the stuff that you need to practice. For the flipped classroom components especially, you should make sure that you have read the session materials linked from this site _before_ the in-person session. This will mean that you will have had time to digest any new concepts and can concentrate on the application of them whilst doing the problem sets in class. Coming to the session to read and do the problem sets in one go will _not_ be to your best advantage. 

## How to make the least of the course

A lot of people with biological training will have already gained some experience in statistical tests or linear models or other data science and bioinformatics. That is great and will be a big help. Some people with biological training who have gained experience of data science and statistical methods will have hated it and come to believe that the whole topic is not for them. Assuming that this course is just a restatement of prior material and that you already know it or that you will never know it are definite ways to miss the particular ways of thinking about data that this course will try to give you. Work with an open mind about what statistics and data science can bring to your science to avoid this. 

## How to work together

Working together is actively encouraged in the sessions, discussing the subjects, the particular problems and mapping out solutions to problems is a great way to come to a better understanding of them. Try to do this vocally with partners or groups, or try to sketch ideas out on paper before committing individual code into the computer.

## How not to work together

Working together should not spill over into assessment submission, code and text submitted for those should be your own work, typed in by your own hand. Copy and Paste from the internet or a shared solution will very likely run foul of University plagiarism rules. 

## How to get a not-so-good mark

The assessment of this course is through an essay and a practical analysis problem. The sorts of problems you'll be asked to solve are discussed very widely across the internet, so when you're under time pressure you might be tempted to try a quick Google to see what those tutorials say and pull those methods into your work verbatim. Doing this not only runs the risk of University plagiarism rules, but also misses the point of much of the teaching. The course teaches some useful and particular ways of thinking about data science that are not so often developed in quick online tutorials. If you rely on the Google Copy and Paste strategy alone and don't show evidence of learning from the TSL course your examiners will likely interpret this as a missed learning outcome. Completely ignoring the materials in the extended section of the course (topics 4, 5 and 6) in your assessment will likely be interpreted as a missed learning outcome too.
