# About {.unnumbered}

Welcome to the TSL Bioinformatics Training Website. 

In here you will find links to the written content for each of the separate topics covered as well as the descriptions of the courses and a guide to helping you work out what you need.


:::{.callout-important}
## Wait - I just want to use the HPC.

That's great! To get an account, email George Deeks and he'll initiate that for you. There's a short induction with George that is compulsory - it aims to help you work out where everything is and acts as a refresher. If you're already capable at the command line it takes about 30 minutes.
:::

:::{.callout-important}
## Uh - I want to use the HPC but don't have command line experience yet.

That's great too, seek out Clara Jégousse and her Intro to Command Line course, this will give you the skills on working at the command line. Once you've got the basics you'll be good to use the HPC.
:::

## Course Delivery

Bioinformatics and Data Science comprise a set of practical research skills grounded in statistics and computer science. Learning a practical skill requires practice! So these courses are not lecture courses, they are a mixture of  'flipped' classroom courses and bootcamp style courses each with a very strong practical component. 
In this framework the onus is on the learner to lead their work and practice with the provided materials prior to contact and discussion time with the wider learning group and group mentors. Contact time will then be an opportunity to discuss the materials and any problems arising with the group and the teacher and to practice and problem solve with others. The aim is that you will have a strong practical grounding in using bioinformatics and data science approaches to research problems that will enhance the biology that you are doing.  

## Online Materials

The rest of this site outlines the online materials provided, broken down by the separate topics we cover. The materials contain a mixture of self-led tutorials and interactive challenges or problems to solve.    

## Installation of software and tools

Most of the topics outline the stuff you will need to install. Sometimes this is fiddly and sometimes it just doesn't work (and often when it doesn't work it isn't because you did something wrong). If you don't feel confident or are having problems see George Deeks and Chris Rickett for help

## Topics

The following topics are covered in our training

    1. Introduction to Bioinformatics on the Command-Line and HPC
    2. Introduction to Online Databases
    3. Data Exploration and Visualisation
    4. Understanding Statistics With Linear Models
    5. Introduction to Non-Frequentist Statistics
    6. Introduction to Machine Learning
    7. Beginning Programming
    8. Literate Computation


None of them are compulsory, all are open to everyone. 

:::{.callout-note}
## Cohorts
We provide our sessions to each TSL cohort separately  - meaning that we generally host separate workshops for Students and Post Docs to reflect the different needs and interests of the different groups. If you're not sure which cohort you should go to, ask us. It may be that we need to organise something specific for you. 
:::

## Upcoming sessions

```{r,echo=FALSE, warning =FALSE, message=FALSE}
library(lubridate)
library(magrittr)
library(gt)
tibble::tibble(
    `Session` = c('Data Exploration and Visualisation', 'Data Exploration and Visualisation', 'Stats with Linear Models', 'Stats with Linear Models', 'Other Topics', 'Other Topics'),
    `Date` = ymd(c("2022-7-5", "2022-7-8", "2022-8-16", "2022-8-18", "2022-9-13", "2022-9-15")),
    `Cohort` = rep(c("PD", "Stu"), 3),
    `Type` = rep(c("Flipped Class Workshop Session"), 6),
    `Start Time` = rep(c("1330"), 6),
    `Location` = rep("G72", 6),
    `Lead` = rep("Dan", 6)
    
) %>% 
    gt() %>% 
        tab_header(
            title = "Upcoming sessions"
        ) %>% 
        fmt_date(
            columns = c(Date)
        ) 
    
```


